### PR TITLE
Allow Go test command for individual tests

### PR DESCRIPTION
**Pull request by ahsu1230**
Got a few complaints that you have to run `go test ./...` just to test specific tests which is a bad experience. Made some changes to allow running of all individual `controllers` and `repos` tests.

So now you can run:
```
go test ./src/controllers/semester_controller_test.go 
go test ./src/repos/semester_repo_test.go 
```

Still figuring out a good way to run individual integration tests. I do have an idea, but it'll take a lot of plumbing to do so (golang subtests)

### CODE REVIEW

**Comment by ahsu1230** [comment]
@austinhsu14 @ChujiaGuo @mythicat554 Please take a look. I just moved a few functions to its own package so now you can run individual controller/repo test files.
I'm still working on running individual integration tests.

Please leave any feedback or questions you may have. At least approve this PR to show me you've read this message.

**Comment by ChujiaGuo** [comment]
From what I can see, a lot of the changes are just sending HTTP requests differently. I'm assuming there's nothing that we will have to change to what we've been working on?

**Comment by mythicat554** [comment]
Looks good to me- excited for this change!

**Comment by ahsu1230** [comment]
> From what I can see, a lot of the changes are just sending HTTP requests differently. I'm assuming there's nothing that we will have to change to what we've been working on?

yup nothing on your part. Just make sure to follow the new convention when writing stuff. Once this change goes in though, you guys might have some merge conflicts. Sorry not sorry! :)

**Pull request merged**
